# Generated by Django 6.0.4 on 2026-05-02 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="chat_pics/"),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="chat_docs/"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_delivered", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Statut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Texte"),
                            ("image", "Image"),
                            ("video", "Vidéo"),
                            ("audio", "Audio"),
                            ("poll", "Sondage"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("contenu", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.FileField(blank=True, null=True, upload_to="status_pics/"),
                ),
                (
                    "audio",
                    models.FileField(blank=True, null=True, upload_to="status_audio/"),
                ),
                ("date_pub", models.DateTimeField(auto_now_add=True)),
                ("date_expire", models.DateTimeField(blank=True, null=True)),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="statut_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "views",
                    models.ManyToManyField(
                        blank=True,
                        related_name="statut_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_pub"],
            },
        ),
        migrations.CreateModel(
            name="SondageOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.CharField(max_length=100)),
                (
                    "votes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="votes_sondage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "statut",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="chat.statut",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PinnedChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pinned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pinned_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pinned_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pinned_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-pinned_at"],
                "unique_together": {("user", "pinned_user")},
            },
        ),
    ]
