# Generated by Django 6.0.4 on 2026-04-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_alter_statut_contenu_alter_statut_image_contact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
