# Generated by Django 6.0.4 on 2026-04-28 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_pinnedchat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="statut",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="status_audio/"),
        ),
        migrations.AddField(
            model_name="statut",
            name="date_expire",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="statut",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Texte"),
                    ("image", "Image"),
                    ("video", "Vidéo"),
                    ("audio", "Audio"),
                    ("poll", "Sondage"),
                ],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="statut",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="statut_views", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="statut",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SondageOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.CharField(max_length=100)),
                (
                    "statut",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="chat.statut",
                    ),
                ),
                (
                    "votes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="votes_sondage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
