# Generated by Django 6.0.4 on 2026-04-28 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_statut_audio_statut_date_expire_statut_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StatutReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        choices=[
                            ("❤️", "Coeur"),
                            ("😂", "Rire"),
                            ("🔥", "Feu"),
                            ("👏", "Applaudir"),
                            ("😮", "Wouah"),
                            ("😢", "Triste"),
                        ],
                        max_length=5,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="chat.statut",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("statut", "user")},
            },
        ),
    ]
