# Generated by Django 6.0.4 on 2026-04-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_notification"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="statutreaction",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="statutreaction",
            name="statut",
        ),
        migrations.RemoveField(
            model_name="statutreaction",
            name="user",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="StatutReaction",
        ),
    ]
